version: '3'
services:
  app:
    depends_on:
      - mysql
    image: ahdock/flask
    container_name: flask_app
    restart: always
    labels:
      project: "flask"
      day: "7 Aug 2022"
    build:
      # build the image from Dockerfile
      context: .
      dockerfile: Dockerfile
    environment:
      # set database, memcached etc credentials
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password123
    volumes:
      - ./app:/app
    links:
      # network connection with these services
      - mysql
    depends_on:
      # build those images first
      - mysql
    ports:
      # bind on our 5000 port because most people have 80, 8080 already bound
      - "5000:5000"
    # networks:
    #   appNetwork:

  mysql:
    container_name: flask_mysql
    image: mysql:8.0.17
    volumes:
        # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    labels:
      project: "flask"
      day: "7 Aug 2022"
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: my_websites
      MYSQL_USER: flask
      MYSQL_PASSWORD: password123
    # networks:
    #   appNetwork:

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    restart: unless-stopped
    labels:
      project: "flask"
      day: "7 Aug 2022"
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: flask
      PMA_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: password123
    # networks:
    #   appNetwork:

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local
# networks:
#   appNetwork:
